name: generate ASCII artwork

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  ascii-job:
    runs-on: ubuntu-latest
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: checkout
        uses: actions/checkout@v4

      # Runs a single command using the runners shell
      - name: install cowsay program
        run: sudo apt-get install cowsay -y
      
      - name: execute cowsay CMD 
        run: cowsay -f dragon "run for cover, I am a DRAGON....RAWR" >> dragon.txt

      - name: test existing file
        run: grep -i "dragon" dragon.txt

      - name: read file
        run: cat dragon.txt

      - name: List Repo File
        run: ls -ltra

      



  hello-job1:
    needs: hello-job
    runs-on: ubuntu-latest
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Runs a single command using the runners shell
      - name: Echo text
        run: echo "Hello, samka!"
      