name: generate ASCII artwork

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    runs-on: ubuntu-latest
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: install
        run: sudo apt-get install cowsay -y

      - name: execute cowsay cmd
        run: cowsay -f dragon "run for cover, I am a DRAGON....RAWR" >> dragon.txt

      - name: upload dragon file
        uses: actions/upload-artifact@v4
        with:
          name: dragon-artifact
          path: dragon.txt


  test:
    needs: build
    runs-on: ubuntu-latest
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: download dragon file
        uses: actions/download-artifact@v4
        with:
          name: dragon-artifact
        

      - name: test file exists
        run: grep -i "dragon" dragon.txt
              


  deploy:
    needs: [test]
    runs-on: ubuntu-latest
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: download dragon file
        uses: actions/download-artifact@v4
        with:
          name: dragon-artifact

      - name: read file
        run: cat dragon.txt

      - name: deploy
        run: echo "###########-depoying-##########-Dragon-###########"
              
      



      